#!/bin/bash

set -e

cd packages/white_whale
cargo update
cargo clippy -- -D warnings
cargo unit-test
cd -

cd contracts/bluna-vault
cargo update
cargo clippy -- -D warnings
cargo unit-test
cargo schema
cd -

cd contracts/gov
cargo update
# cargo clippy -- -D warnings
cargo unit-test
cargo schema
cd -

cd contracts/buy-and-burn
cargo update
cargo clippy -- -D warnings
cargo unit-test
cargo schema
cd -

cd contracts/stablecoin-vault
cargo update
cargo clippy -- -D warnings
cargo unit-test
cargo schema
cd -

cd contracts/profit-check
cargo update
cargo clippy -- -D warnings
cargo unit-test
cargo schema
cd -

cd contracts/vesting
cargo update
# cargo clippy -- -D warnings
cargo unit-test
cargo schema
cd -

cd contracts/gov
cargo update
# cargo clippy -- -D warnings
cargo unit-test
cargo schema
cd -