#!/bin/bash

set -e

cd contracts/stablecoin-vault
cargo update
cargo clippy -- -D warnings
cargo unit-test
cargo schema
cd -

cd contracts/vesting
cargo update
# cargo clippy -- -D warnings
cargo unit-test
cargo schema
cd -
